### ISSUE TITLE
Linux64 make error: multiple Io definitions

### ISSUE THREAD

**Issue by MrMormon** [createuniverses/praxis#5]
I ran qmake first, without issue. But make exits with [this huge error](http://paste2.org/56FanfgE).

**Comment by createuniverses** [comment]
I don't have a 64 bit linux machine to test this on, but that link error appears to result from inline functions being defined in all those object files.

Open ```io/Common_inline.h```, and in the ```#if defined(__APPLE__)``` block starting on line 53, see which section is defined for your computer + compiler combination. This block defines ```IOINLINE```. Your error might be fixed by going to the end of that block (which is the end of the file) and overriding it by adding the line ```#define IOINLINE static inline```

**Comment by MrMormon** [comment]
Thanks! I'll have to give this a try.

**Comment by MrMormon** [comment]
I added `#define IOINLINE static inline` and `#define IOINLINE_RECURSIVE static inline` to the end if the file and make worked! But now:
```
In MemoryBlock(size_t). length = 25.
In MemoryBlock(MemoryBlock&&). length = 25. Moving resource.
In ~MemoryBlock(). length = 0.

Hello from the input thread.

In MemoryBlock(size_t). length = 75.
In MemoryBlock(MemoryBlock&&). length = 75. Moving resource.
In MemoryBlock(const MemoryBlock&). length = 25. Copying resource.
In ~MemoryBlock(). length = 25. Deleting resource.
In ~MemoryBlock(). length = 0.
In MemoryBlock(size_t). length = 50.
In MemoryBlock(MemoryBlock&&). length = 50. Moving resource.
In MemoryBlock(const MemoryBlock&). length = 25. Copying resource.
In MemoryBlock(const MemoryBlock&). length = 75. Copying resource.
In ~MemoryBlock(). length = 25. Deleting resource.
In ~MemoryBlock(). length = 75. Deleting resource.
In ~MemoryBlock(). length = 0.
In ~MemoryBlock(). length = 25. Deleting resource.
In ~MemoryBlock(). length = 50. Deleting resource.
In ~MemoryBlock(). length = 75. Deleting resource.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  47
  Current serial number in output stream:  48
```
The computer I'm running this on only has OpenGL 2.1 - is that the problem?

**Comment by createuniverses** [comment]
See: https://github.com/createuniverses/praxis/issues/4

> In SingleWorldConfiguration.cpp, try changline line 87 from:
> ```glutInitDisplayMode( GLUT_RGB | GLUT_SINGLE | GLUT_DEPTH | GLUT_OFFSCREEN | GLUT_STENCIL);```
> to:
> ```glutInitDisplayMode( GLUT_RGB | GLUT_SINGLE | GLUT_DEPTH );```
